### ISSUE TITLE
Importing utils_scFAN and data_iter_scFAN instead of utils and data_iter?

### ISSUE THREAD

**Issue by KatharinaSchmid** [sperfu/scFAN#1]
Hi,

we tried to run a training with scFAN (using python3_codes/scFAN_train.py), but had multiple issues so far; for example the way the pybedtools tmp directory is set in utils.py (pybedtools.set_tempdir('/data1/fly/tmp') in line 14) and now in the training the dimensions from the data iterator are not correct:

```
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays
```

In scFAN_train.py, currently the functions from utils.py and data_iter.py are imported, however the directory contains also the files utils_scFAN.py and data_iter_scFAN.py. It looks like the issues are fixed in utils_scFAN.py and data_iter_scFAN.py. Is it possible that instead these files should be imported in scFAN_train.py? Or do you know what else could have caused the ValueError in the training?

Thank you for your help!

Regards,
Katharina

**Comment by sperfu** [comment]
Hi Katharina,
Thanks for the question, I think there are two ways to solve the problem. Firstly, you probably need to change the tempdir to your own directory(such as : pybedtools.set_tempdir('/your_own_directory') in both utils.py and utils_scFAN.py), these are temp files location; Secondly,both utils.py and data_iter.py are for training(used in scFAN_train.py) and utils_scFAN.py and data_iter_scFAN.py are designed for predicting(used in scFAN_predict.py).  Also, there are multiple inputs passed into the model, please see the tutorial in the Read.me and data folder( https://github.com/sperfu/scFAN/tree/master/Data). 

Thanks,
Laiyi

**Comment by KatharinaSchmid** [comment]
Hi Laiyi,

thanks for your help. Yes, we set the tempdir to our own directory and that solved the first part of our issue. But we still get the ValueError that I described above. I don't fully understand why you use in data_iter.py the forward and reverse strand as input `batch_x = [batch_X_fwd, batch_X_rev]` but in data_iter_scFAN.py only the forward strand `batch_x = batch_X_fwd`. Is it not necessary that the input matrix in training and prediction have the same dimensions?

But I guess it would be easier if I test instead your trained models and see if this is working (it would be great if you could grant me access to your google drive for that).

Regards,
Katharina

**Comment by sperfu** [comment]
Hi Katharina,

thanks for the notice. We're glad that you point it out, it's really a version upload mistake, I uploaded a former comparison model's version of data_iter.py. I have corrected that mistake and right now it should be consistent output dimension in both training and testing.   Also, we have also uploaded all the pretrained model into the google drive folder, you may check ( https://github.com/sperfu/scFAN/blob/master/Data/Readme.md) for the details or directly download them at (https://drive.google.com/open?id=1R9V53HgpdrjYdFJ04nF_BxjaUfVI7LI1).

Thanks,
Laiyi

**Comment by KatharinaSchmid** [comment]
Hi Laiyi,

thanks for fixing the issue and for sending me the link to your pertained models.

Regards,
Katharina
