### ISSUE TITLE
Predicting bulk ATAC data

### ISSUE THREAD

**Issue by tianqiyy** [sperfu/scFAN#2]
Hi, 
I wonder can scFAN predict TF binding for bulk ATAC-seq data? if it can, could you please provide an example of the script and data preparation?
Thanks!
Tianqi

**Comment by sperfu** [comment]
Hi Tianqi,

Thanks for the suggestion. Even though our scFAN model is primarily designed for predicting single cell data, the pretrained model is fully capable of predicting TF binding for bulk ATAC-seq data as well, we are updating another script named: predict_bulk_TF.py in the main folder, you can use that script to predict TF binding using bulk ATAC-seq data. For all the input data, you need first download or use your own data and put them into the Data folder as mentioned in  [Data folder](https://github.com/sperfu/scFAN/blob/master/Data), noted that don't forget to put the chromsome fasta data and other resources data into that folder as well, which can also be downloaded from [our drive](https://drive.google.com/drive/folders/1R9V53HgpdrjYdFJ04nF_BxjaUfVI7LI1).

Thanks,
Laiyi

**Comment by tianqiyy** [comment]
Thank you!
